### ISSUE TITLE
Detecting running in dark mode or not

### ISSUE THREAD

**Issue by Kanahiro** [maptiler/qgis-maptiler-plugin#10]
related https://github.com/maptiler/qgis-maptiler-plugin/issues/3#issuecomment-626705712

There are icons separately to be used in dark mode or not.
It is better to detect in dark or not in the plugin.

**Comment by Kanahiro** [comment]
I'm not sure whether it is possible or not.
Firstly I'll research about it.

**Comment by Kanahiro** [comment]
Although it is apparently impossible to simply detect in dark mode or not in Qt, I can get a background RGB value of a dialog.
QtWidget -> palette() -> window() -> red(), green(), blue()
So it is possible to judge background-color is lighter or darker.

Then, in this way  I'll add some codes to judge which icon should be used.

**Comment by klokan** [comment]
Excellent workaround @Kanahiro ! Thanks. 👍

**Comment by klokan** [comment]
Implemented #15
