### ISSUE TITLE
QGIS crash with maptiler plugin installed

### ISSUE THREAD

**Issue by nilsnolde** [maptiler/qgis-maptiler-plugin#100]
QGIS kept crashing while rendering base maps after I installed maptiler. When I uninstalled it QGIS was working normally again.

To reproduce:
1. Simple project with **any** basemap, from MapTiler or QMS
2. Zoom around to load uncached tiles
-> QGIS infinitely tries to render/load and eventually I have to force close

The issue entirely resolved when I uninstall maptiler. Only deactivating the plugin is not a solution. As far as I can tell the issue pops up when new (uncached) tiles have to be rendered. 

Let me know if any other information on my system would be useful to track this down. 

My personal guess is that #80 has smth to do with it. However, why it's even happening with QMS base maps is really mysterious and wouldn't be explained by that.. Are you somehow manipulating any core-wide settings for rendering or caching (if that's even possible)? 

QGIS info:
```
QGIS version | 3.12.3-București | QGIS code branch | Release 3.12
-- | -- | -- | --
Compiled against Qt | 5.15.0 | Running against Qt | 5.15.0
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.32.1 | Running against SQLite | 3.32.2
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Manjaro Linux
Active python plugins | quick_map_services; plugin_reloader; ORStools; qgis-maptiler-plugin; QuickOSM; MetaSearch; db_manager; processing
```

**Comment by lazaa32** [comment]
Hi Nils,
I tried to reproduce your steps but it works just fine for me.
- Do you get any error messages in QGIS Python Console, stderr or Development/Debugging tools?
- Does it crash if you zoom straight into high levels? Does it crash if you zoom slowly zoom by zoom or two?
- Is there any proxy on your network?

**Comment by nilsnolde** [comment]
This is a weird issue. I can confirm now that it's not MapTiler, the same happens with Carto's maps. And it's clear now, that it's definitely related to how fast you zoom in. Zooming in _very_ slowly and it works fine. Thanks for the hint. 

Though with Carto's maps it doesn't happen as consistently as with MapTiler, i.e. sometimes Carto maps get stuck, sometimes they don't. OSM base map works entirely fine. MapTiler really freezes QGIS every time I zoom in "too fast".

I have a 100Mb connection and don't think lag is a problem (unless yours and Carto's server are hosted in Australia, which I guess they aren't; I'm in Berlin). Also, my laptop is very new Lenovo T495s. Interestingly I can't reproduce with OSM base layer from QMS, suggesting it's a tile serving issue (coupled with a general minor bug how the plugin(s) load the tiles maybe across all those zoom levels when zooming in fast ?). 

To answer your other questions:
- No error in the Python console or the Log Message panel. Not sure how to access other QGIS debug info. Happy to do though if you provide some guidance. I have a `master` build here from a couple of weeks ago and can tweak compiler flags if really necessary.
- That's answered I guess
- No proxy

**Comment by lazaa32** [comment]
Could you try press F12 to display Debugging/Development Tools?
Try to zoom in and out if there are any error requests.

**Comment by nilsnolde** [comment]
Seems like that's only available from QGIS 3.14? 
`Note: since version 2.1.4 this is Ctrl+F12 because F12 is used by development tools dock in QGIS >= 3.14`
Ref https://github.com/wonder-sk/qgis-first-aid-plugin

Would have to build master for that. Not available in arch repos (since not released yet I guess). I'll wait a few days, release is on 19.06. OK?

**Comment by lazaa32** [comment]
You are probably right. I tried it in QGIS 3.4 and couldn't find Debugging tools there either. Never mind, it could give us some clue however I will dig whether there is any issue on tile serving on our side.

**Comment by nilsnolde** [comment]
Hm, tried it again now and it seems to just work, same laptop, QGIS version and internet connection. Even when zooming in it loads for a bit, I get scared a little, but then it resolves the tiles nicely:)

Closing as long as it doesn't re-appear.

**Comment by nilsnolde** [comment]
It's still happening.. During daytime the maps from this plugin and QuickMapServices become unusable for me. As soon as I zoom in/out per mouse wheel it'll freeze QGIS, getting stuck in the rendering loop.

You think #80 could be the culprit? I haven't been using QGIS too much lately, but I can for sure say it hasn't been an issue with QMS in 3.4 (now using 3.12, arch still didn't update to 3.14).

**Comment by lazaa32** [comment]
As you stated there is no proxy on your network, #80 should not be related to your issue. I would suggest to wait for 3.14 or build it from source if arch is not going to update the repos soon. Step by step installation manual available at QGIS [github](https://github.com/qgis/QGIS/blob/master/INSTALL.md).
