### ISSUE TITLE
Maps do not load and QGis does not react on MacOS 10.15.5 

### ISSUE THREAD

**Issue by petermorlock** [maptiler/qgis-maptiler-plugin#109]
When trying to add a layer the Maps do not load and QGis does not react on MacOS 10.15.5.

**Comment by lazaa32** [comment]
Could you please provide more details such as:
- QGIS version
- Do you try to add preset map or a custom map from URL?
- If preset map, do you have valid key?
- Any error messages in Python console?
- Any proxy on your network?
Thank you @petermorlock

**Comment by petermorlock** [comment]
QGIS version = 3.14
Do you try to add preset map or a custom map from URL? - Yes a preset map
If preset map, do you have valid key? I use one of my key generated in MapTiler Cloud.
Any error messages in Python console? No

Any proxy on your network? No

I have just tried it again. And now it works!

Thanks lazaa32, without your reply I'd have not tried again.
