### ISSUE TITLE
First QGIS styling of vector tiles with Mapbox GL style using mapbox2qgis

### ISSUE THREAD

**Issue by klokan** [maptiler/qgis-maptiler-plugin#11]
Let's test and integrate the library
https://github.com/wonder-sk/mapbox2qgis
with this plugin.

It seems to provide relatively reasonable results: 
![ezgif-5-f9340f0a7946](https://user-images.githubusercontent.com/59284/82297761-64596f80-99b3-11ea-93d4-8fac617b9963.gif)
https://twitter.com/lutraconsulting/status/1250777717815025665

Additional improvement can be done by an improvement of this library of integration of an alternative.

The steps here are:
- [ ] Style the "Basic" vector tile map preset
- [ ] Add more presets styles (including Street and Satellite Hybrid - which are going to require grouped style with raster and vector layers in QGIS, etc.)
- [ ] Add support for styling user-supplied style (provided as a web link / URL under "New connection" - while supporting any online GL Style, including self-hosted instances - for example, [OpenMapTiles Server](https://openmaptiles.com/server/), GeoServer, TileServer GL or alternative hosting providers)
- [x] Experiment with #12 and #13 and decide how to improve the style conversion further

**Comment by klokan** [comment]
Decision: we are going to further improve your library, @wonder-sk, after fast review of bridge-style in #12 and style-convertor in #13 

@lazaa32 has an initial implementation - to be pushed via PR here.

**Comment by wonder-sk** [comment]
Cool - it would be good to do a bit more thorough review of features of mapbox gl style that are missing in that conversion script. Some bits would be worth implementing in c++ directly in qgis core - particularly expression functions that would be called a lot (and having them just in python would slow down rendering quite a bit). If I remember correctly, for example, the built-in interpolation function does not support intermediate stops. Even now during qgis feature freeze it should not be a problem to get such small under the hood improvements merged before the final release in ~3-4 weeks.

**Comment by Kanahiro** [comment]
Now, all lines in vector tile layer always have minimum width 0.
In gl2qgis.py, line-width defined with Key - QgsSymbolLayer.PropertyWidth, but this apparently don't mean Line-width and, to define line-width, PropertyStrokeWidth should be used.

This screenshot is after changing to PropertyStrokeWidth, as you see line-width correctly defined.

<img width="400" alt="スクリーンショット 2020-05-28 11 21 39" src="https://user-images.githubusercontent.com/20744195/83091187-99617280-a0d5-11ea-9e60-5d0df0492a53.png">
<img width="400" alt="スクリーンショット 2020-05-28 11 21 55" src="https://user-images.githubusercontent.com/20744195/83091200-9cf4f980-a0d5-11ea-966c-7d1801b5dfe3.png">

**Comment by lazaa32** [comment]
Closed in #85.

**Comment by klokan** [comment]
Thank you very much!
