### ISSUE TITLE
Unable to change label styles in vector tiles

### ISSUE THREAD

**Issue by sdbernard** [maptiler/qgis-maptiler-plugin#110]
QGIS 3.14 using custom style which I edited on maptiler website.
https://api.maptiler.com/maps/41ec7587-5688-4f26-9de8-92ede5f5cdc7/style.json?key=IoyNas5xFwEQfz7OZVzh

When I go to edit the openmaptiles layer the labels setting aren't editable. 

![image](https://user-images.githubusercontent.com/2511348/85551875-57671600-b61a-11ea-998f-57e97a054a9c.png)

Double-clicking on any of the settings doesn't bring up the label options, so I am unable to change font, size, style etc. I can edit the filter text but I would expect to be able to edit everything else in the usual labels panel...

![image](https://user-images.githubusercontent.com/2511348/85552858-55ea1d80-b61b-11ea-817b-7f791cbef165.png)

The symbology editing is fine however

**Comment by wonder-sk** [comment]
That's a bug in QGIS... I must have missed that. Could you please file a ticket in QGIS issue tracker?

Normally I use 'Layer Styling' dock widget (you can open it also with F7 shortcut) and there it works for labeling when you double-click on a labeling style. Another advantage of the dock widget is that it does live update by default.

**Comment by lazaa32** [comment]
> That's a bug in QGIS... I must have missed that. Could you please file a ticket in QGIS issue tracker?
> 
> Normally I use 'Layer Styling' dock widget (you can open it also with F7 shortcut) and there it works for labeling when you double-click on a labeling style. Another advantage of the dock widget is that it does live update by default.

Thank you @wonder-sk for suggested workaround, ticket created at https://github.com/qgis/QGIS/issues/37386.

**Comment by wonder-sk** [comment]
#37399

**Comment by sdbernard** [comment]
Layer styling panel works perfectly thank you

**Comment by lazaa32** [comment]
Work-around described above. Closing for now.
