### ISSUE TITLE
Roads are not coming through properly on vector tiles

### ISSUE THREAD

**Issue by sdbernard** [maptiler/qgis-maptiler-plugin#111]
QGIS 3.14 using custom style which I edited on maptiler website.
https://api.maptiler.com/maps/41ec7587-5688-4f26-9de8-92ede5f5cdc7/style.json?key=IoyNas5xFwEQfz7OZVzh

When I import the tiles into QGIS the roads are very patchy and many are missing altogether

Compare the QGIS view to the view of the same map style on MapTiler website

QGIS
![image](https://user-images.githubusercontent.com/2511348/85554222-9b5b1a80-b61c-11ea-98f6-66666898edc0.png)

MapTiler website
![image](https://user-images.githubusercontent.com/2511348/85554280-a9a93680-b61c-11ea-9831-da141504940e.png)

**Comment by lazaa32** [comment]
I tried your style in new version of plugin (v1.1.1) and it looks quite similar. What is your version of plugin? Sometimes tiles are not completely rendered and you need to zoom in and out or pan map to rerender.
Also GL style is quite complex and QGIS does not support all the expressions and so far it is not possible to translate GL json style to QGIS styling. We are trying to improve style translation step by step but there are few things that are not possible to do in QGIS (icons, more complex interpolation functions etc...)

![image](https://user-images.githubusercontent.com/19833762/85978108-3e75b080-b9de-11ea-9329-280ec0756fef.png)

**Comment by sdbernard** [comment]
Thanks for this Adam, good to know that icons don't work yet. I was wondering what was breaking the plugin. I've started again with a new style and I'm getting very close to what I'm hoping to achieve. 

So are icons something that is simply not possible to achieve? Or is it dependent on development of QGIS itself?

**Comment by lazaa32** [comment]
In general QGIS supports old/legacy [functions and filters](https://docs.mapbox.com/mapbox-gl-js/style-spec/other/) better. It can handle them better and styling is faster however style.json is then usually longer as you can't you expressions to simplify it.
Plugin works in a way that if there is any expression in style.json that plugin has problem to parse it just skip it and set a default value to property (line-width=1, opacity=1.0 etc...). 
Regarding icons, QGIS does not support their collapsing so far. So it is not a problem to add an icon to a feature but on lower zooms you would end up with map full of icons.
