### ISSUE TITLE
Labels not showing correct language

### ISSUE THREAD

**Issue by sdbernard** [maptiler/qgis-maptiler-plugin#115]
QGIS 3.14 using custom style which I edited on maptiler website.
https://api.maptiler.com/maps/47b20404-cb5f-4244-bb1e-110968bf9fbb/style.json?key=IoyNas5xFwEQfz7OZVzh

I set the language to English and turned off include alternative names. The web preview on MapTiler is fine
![image](https://user-images.githubusercontent.com/2511348/85859921-d5135900-b7b5-11ea-9117-23e7d5db2c56.png)

But when I pull the style into QGIS it still has a mixture...
![image](https://user-images.githubusercontent.com/2511348/85860028-fecc8000-b7b5-11ea-8c84-ee1a3dc93f88.png)

**Comment by lazaa32** [comment]
Related to #108. One of the feature which is planned  to be implemented in next release.

**Comment by klokan** [comment]
I consider this to be a bug.

If you have a customized map (not one of the standard maps) with explicitly set language of labels - the QGIS should load is as it is - instead of doing a magic with locale in local QGIS perhaps.

**Comment by cogitoxin** [comment]
Any update on this issue? I changed the language of my qgis and the labels are still in English. This feature is very important to me so please help!

**Comment by lazaa32** [comment]
Hi @cogitoxin and @sdbernard ,

you can manually fix this by open Layer Styling Panel (press F7). 
Choose the label layer you want to fix (e.g. `contry_label`) and change its Value. By default it is `name:latin` but you can choose `name:en`, `name_int`, `name_en`... whatever suits you the best.
![image](https://user-images.githubusercontent.com/19833762/99964304-5ede4700-2d93-11eb-8caf-b8a72c97114c.png)

Please let me know if this works for you.

**Comment by cogitoxin** [comment]
> Hi @cogitoxin and @sdbernard ,
> 
> you can manually fix this by open Layer Styling Panel (press F7).
> Choose the label layer you want to fix (e.g. `contry_label`) and change its Value. By default it is `name:latin` but you can choose `name:en`, `name_int`, `name_en`... whatever suits you the best.
> ![image](https://user-images.githubusercontent.com/19833762/99964304-5ede4700-2d93-11eb-8caf-b8a72c97114c.png)
> 
> Please let me know if this works for you.

Thanks But...actually I need the labels in Chinese. I tried to change name:latin to name:ch but it did not work. Any workaround?

**Comment by Dylan-Cairns** [comment]
> > Hi @cogitoxin and @sdbernard ,
> > you can manually fix this by open Layer Styling Panel (press F7).
> > Choose the label layer you want to fix (e.g. `contry_label`) and change its Value. By default it is `name:latin` but you can choose `name:en`, `name_int`, `name_en`... whatever suits you the best.
> > ![image](https://user-images.githubusercontent.com/19833762/99964304-5ede4700-2d93-11eb-8caf-b8a72c97114c.png)
> > Please let me know if this works for you.
> 
> Thanks But...actually I need the labels in Chinese. I tried to change name:latin to name:ch but it did not work. Any workaround?

I have the exact same issue, cannot display Chinese labels.

According to [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) it should be 'zh' not 'ch'. 

But I still cannot get it to work.

**Comment by cogitoxin** [comment]
@Dylan-Cairns Thanks! For me "name_en" only worked for some cities but "name:zh" + '\n' + "name:latin" worked perfectly.
I changed the labels manually and saved layer style to avoid manually changing labels every time. 

![image](https://user-images.githubusercontent.com/16520525/112251506-55f47800-8c96-11eb-9b70-04fedfc4aaaa.png)

**Comment by Dylan-Cairns** [comment]
@cogitoxin glad to help. Did you have to do anything to get 县 and 区 to appear on your map? I can't figure out how to get them to show up on mine.

**Comment by cogitoxin** [comment]
@Dylan-Cairns These are my settings to show villages and towns: 
![image](https://user-images.githubusercontent.com/16520525/112290979-b1405d80-8cca-11eb-9e9a-a0d40390274d.png)
