### ISSUE TITLE
zoom level changes in layout when zooming view

### ISSUE THREAD

**Issue by lukaszkruk** [maptiler/qgis-maptiler-plugin#117]
Hello Maptiler,

Thanks for the fantastic plugin. This is a really useful piece of software, and great map layers too.

I'm using QGIS 3.12 with your non-vector tiles on Windows 10. 

Map in layout view changes the tile zoom level used when I zoom in and out the layout view. So the layout page gets smaller and larger, where I would expect my map elements to stay consistent. 

When exporting to PDF, the labels are tiny. 

Throughout this process, the scale of the map item is not changed. 

How can I lock the tile layer zoom level and have it behave predictably, or get a WYSIWYG behaviour for pdf exports? If there is a way, I believe it should be the default behaviour.

**Comment by lazaa32** [comment]
Hi @lukaszkruk 

Unfortunately I can't answer your question. Changing of map while zooming in and out in layout view is a normal behaviour, same for WMTS service or XYZ Tiles. I would direct you to QGIS user mailing list as there should be someone more experienced than me who might know how to lock layout at specific zoom level.
I would also encouraged you to upgrade to QGIS 3.14 with vector tiles support as vector tiles are much better for printing. You can also change the size, color, font... of labels to suit you best with vector tiles.

**Comment by lazaa32** [comment]
Closing for now. Feel free to reopen in case of any further concerns.
