### ISSUE TITLE
Toner map blurred

### ISSUE THREAD

**Issue by GalGend** [maptiler/qgis-maptiler-plugin#119]
Gi guys! many thanks for the amazing plugin- it is very useful!

Using QGIS 3.12.13

All maptiler maps from the extension are blurred. Zooming in and out extent changes but remains blurred.

![image](https://user-images.githubusercontent.com/22238092/86178264-fa8ac480-bb1f-11ea-8cb6-f6262d8bea41.png)

**Comment by lazaa32** [comment]
Hi @GalGend,
which version of  plugin do you use? Please make sure it is the latest one (v1.1.1 atm).
Also it looks that you use QGIS on Mac so there might be an issue with retina display. Preset MapTiler maps are served as 256x256 tiles by default which might not look that great on retina display.
You can try to add 512x512 tiles as on this [gif](https://miro.medium.com/max/1400/1*cuYJMGMc9NrQKfYLd3xc6g.gif).

- Click on MapTiler plugin -> `Add new map...`
- In tab `From URL` add map name e.g. Toner512 and insert this link: https://api.maptiler.com/maps/toner/tiles.json?key= into JSON URL (you must have valid API key)
- Click OK to add map to MapTiler plugin and from that double-click on Toner512

Let us know if that solved your issue.

**Comment by GalGend** [comment]
Hi @lazaa32,

Thank you for your reply.
Apparently the layers were rendered as raster layers rather than tile vectors. I upgraded my QGIS to 3.14 and not it presents the layers as tile vectors.

Many thanks,
Gal

**Comment by lazaa32** [comment]
Hi @GalGend,

yes, QGIS started support vector tiles in 3.14. MapTiler plugins works only with raster tiles for older version of QGIS. 
In QGIS 3.14 MapTiler works with vector layers by default however you can either set raster by default in `Account...` window or from preset map right click -> Add as raster.

If you are happy with vector tiles now feel free to close this issue. Thank you.
