### ISSUE TITLE
Try geocat/bridge-style Mapbox GL to QGIS style conversion library

### ISSUE THREAD

**Issue by klokan** [maptiler/qgis-maptiler-plugin#12]
For conversion of a GL style to QGIS, there are multiple alternative libraries we can try and reuse - instead of / in addition to mapbox2qgis from #11 

In this ticket please try bridge-style from https://github.com/GeoCat/bridge-style - btw used in qgis2web plugin at https://github.com/tomchadwin/qgis2web/tree/master/qgis2web

**Comment by lazaa32** [comment]
It seems that bridge-style uses "geostyler" format as a medium for converting from one format to another.
qgis2web uses this libraries to convert QGIS style to MapBoxGL (or Leaflet/OL) as follow:
`QGIS style -> geostyler -> MapBoxGL` and it works fine.
For our case we need opposite direction `MapBoxGL -> geostyler -> QGIS` style which unfortunately is not implemented yet. See [bridgestyle/qgis/fromgeostyler.py](https://github.com/GeoCat/bridge-style/blob/e8b1972b2af26dba6c58e33bc886ac392655300c/bridgestyle/qgis/fromgeostyler.py#L1)

**Comment by klokan** [comment]
Thank! Unfortunately unusable for now. Closing.
