### ISSUE TITLE
Polygon styled as line are filled rather than outline

### ISSUE THREAD

**Issue by frodrigo** [maptiler/qgis-maptiler-plugin#123]
```json
{
  "id": "park-outer",
  "type": "line",
  "source": "openmaptiles",
  "source-layer": "park",
  "paint": {
    "line-color": "rgba(125, 184, 127, 1)",
    "line-width": 6
  }
}
```

Polygon are filled but the layer type is `line`.

On QGis
![imagen](https://user-images.githubusercontent.com/1785486/86919797-11857400-c129-11ea-9464-960d729ee9d9.png)

Expected, on Mapbox GL:
![imagen](https://user-images.githubusercontent.com/1785486/86919888-2cf07f00-c129-11ea-8a6c-f3957d966f7d.png)

On line:
- https://vecto-dev.teritorio.xyz/styles/teritorio-tourism-dev/#8.31/44.644/-0.983
- https://vecto-dev.teritorio.xyz/styles/teritorio-tourism-dev/style.json

**Comment by lazaa32** [comment]
Hi @frodrigo 
it seems that the problem is actually in layer `park-fill` which does not get its defined opacity.
```
"fill-opacity":{"stops":[[6,0],[7,0.3],[9,0]]}
```
Quick work-around is to open Layer Styling Panel (F7 button) and set opacity to layer `park-fill` manually.
I will keep digging and as soon as I found the problem I let you know.

**Comment by lazaa32** [comment]
Hi @frodrigo 
I fixed opacity so layer park-fill gets its correct opacity now. This will be included in next fix release this week. 
![image](https://user-images.githubusercontent.com/19833762/87910930-1b816e00-ca6b-11ea-825e-d753e8f5b6fd.png)
However it seems that QGIS cannot handle polygon features (source layer `park`) and add them styling for lines (`park-inner`, `park-outer`). 
You can still get your desired style manually in layer styling as in picture. I added two simple outlines, with +/- offset, same width, color and 50% opacity for inner outline. It is only a static style though, it means that the style won't disappear on zooming in/out.

![image](https://user-images.githubusercontent.com/19833762/87911825-897a6500-ca6c-11ea-984a-61321502ff63.png)

**Comment by frodrigo** [comment]
Nice. Thank you.
