### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by Polisson** [maptiler/qgis-maptiler-plugin#125]
Clean install of: 
- pop_OS 20.04,
- Python 3.8.2,
- Qgis by flatpak:

QGIS version | 3.14.0-Pi | QGIS code revision | 9f7028fd
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 12.2 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | KDE Flatpak runtime
Active python plugins | ImportPhotos; autoSaver; processing; db_manager; MetaSearch

The setup produces such an error on startup, without any further actions (plugin doesn't work obviously):

```
Couldn't load plugin 'qgis-maptiler-plugin' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'PIL' 
Traceback (most recent call last):
  File "/app/share/qgis/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/mtp/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/__init__.py", line 35, in classFactory
    from .maptiler import MapTiler
  File "/app/share/qgis/python/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/mtp/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/maptiler.py", line 34, in 
    from .browser_root_collection import DataItemProvider
  File "/app/share/qgis/python/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/mtp/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/browser_root_collection.py", line 7, in 
    from .browser_mapitem import MapDataItem
  File "/app/share/qgis/python/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/mtp/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/browser_mapitem.py", line 11, in 
    from .gl2qgis import converter
  File "/app/share/qgis/python/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/mtp/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/gl2qgis/converter.py", line 19, in 
    from PIL import Image
  File "/app/share/qgis/python/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'PIL'


Python version: 3.7.4 (default, Nov 10 2011, 15:00:00) [GCC 9.2.0] 
QGIS version: 3.14.0-Pi Pi, 9f7028fd 

Python Path:
/app/share/qgis/python
/home/mtp/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
/home/mtp/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins
/app/share/qgis/python/plugins
/usr/lib/python37.zip
/usr/lib/python3.7
/usr/lib/python3.7/lib-dynload
/usr/lib/python3.7/site-packages
/app/lib/python3.7/site-packages
/app/lib/python3.7/site-packages/numpy-1.14.3-py3.7-linux-x86_64.egg
/app/lib/python3.7/site-packages/MarkupSafe-1.0-py3.7-linux-x86_64.egg
/home/mtp/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
```

**Comment by lazaa32** [comment]
It looks like a missing PIL library. Could you try to install it and try again?
The easiest way is using pip from terminal:
`pip install Pillow==2.2.2￼`

**Comment by brylie** [comment]
Pillow 7.0.0 is already installed on my system, but the error persists.

[Pillow 2.2.2](https://pypi.org/project/Pillow/2.2.2/) was released Dec 17, 2013.

![image](https://user-images.githubusercontent.com/17307/88282680-ad4edc80-ccf2-11ea-9afa-bef137b151fe.png)

Perhaps the `qgis-maptiler-plugin` could update it's the Pillow dependency to the latest 7.x series?

**Comment by brylie** [comment]
@Polisson On further inspection, I have also installed QGIS via Flatpak. The default Python environment in the QGIS Flatpak does not include Pillow, so it needs to be installed with the following command:

```
flatpak run --command=pip3 org.qgis.qgis install Pillow --user
```
After running the above command, QGIS successfully loads with the MapTiler plugin.

@lazaa32 I still believe it is advisable to test this plugin with the latest stable series of Pillow (7.x) rather than rely on the deprecated 2.x series.
