### ISSUE TITLE
Export as pdf or img

### ISSUE THREAD

**Issue by Pitaya4** [maptiler/qgis-maptiler-plugin#127]
Hi!

QGIS 3.14 
In the map composer:
![1](https://user-images.githubusercontent.com/12743108/87997860-ea7d5980-cabb-11ea-8473-c4d2b999f934.PNG)
But when export as pdf or as image, the map exceeds the frame
![2](https://user-images.githubusercontent.com/12743108/87997862-ee10e080-cabb-11ea-9047-d0975f4db6f3.PNG)

**Comment by lazaa32** [comment]
Hi @Pitaya4 
map composer is powerful tool but sometimes is tricky even for me :) If you need just to export do pdf or image without any furher modification I would suggest you to use export option.
Zoom into location so map canvas covers your desired area. Then click in top menu Project->Import/Export->Export Map to PDF...
Then you can choose which extent you want to export. By default is map canvas extent, but you can change it manually or draw it on canvas.
Please let me know it this is solution for you.

**Comment by KyleHearing** [comment]
I am having the same issue with my inset maps; any insight into how that can be resolved? 
[Example.pdf](https://github.com/maptiler/qgis-maptiler-plugin/files/4953677/Example.pdf)

**Comment by lazaa32** [comment]
Sorry for late answer.
I tested it with MapTiler plugin and got the same issue. However then I tested it with raw non-styled vector tiles and I got the same problem.
Map Composer:
![map_composer](https://user-images.githubusercontent.com/19833762/91857861-cb501b00-ec68-11ea-9e44-b8d5d38c88c1.png)

Exported image:
![Layout 2](https://user-images.githubusercontent.com/19833762/91857872-ce4b0b80-ec68-11ea-9e36-eb8f2d7708a3.png)

I would suggest you to create a ticket at QGIS issue tracker and add it a vector-tiles tag as this is not related to MapTiler plugin but vector-tiles.
Maybe @wonder-sk has an idea what is wrong?

**Comment by wonder-sk** [comment]
Yeah it's possible that clipping rectangle is not set correctly and the map content is drawn also outside of the map layout item. As @lazaa32 suggested, please open a ticket in QGIS tracker with steps how to reproduce it, ideally with a test project.

**Comment by nyalldawson** [comment]
This was fixed upstream in QGIS
