### ISSUE TITLE
qgis2web and maptiler plugins compatible ?

### ISSUE THREAD

**Issue by jipexu** [maptiler/qgis-maptiler-plugin#128]
HI
for information
https://github.com/tomchadwin/qgis2web/issues/907
Thanks

**Comment by lazaa32** [comment]
Hi @jipexu,

MapTiler plugin can partly transform the GL style into QGIS style. I've never tested the compability with qgis2web. As far as I know the qgis2web does the opposite way - convert QGIS style into GL style. I think that if you want to use both maptiler plugin and qgis2web you have to go twice through conversion of the style format which is not ideal. Can you tell me what is your use-case?

**Comment by jipexu** [comment]
@lazaa32 
Thanks for your answer as i wrote here tomchadwin/qgis2web#907 in QGIS i have no probleme with maptiler plugin but when i want to export by Qgis2web for openlayer or leaflet i get python errors... 
As python is not my cup of tea i dont known what is wrong... Probably the nested architecture of the layers provided by maptiler (Contours, hillshade,  MaptilerPlanet,  background....and it seems that Qgis2web dont like the contours layer) is not compatible with Qgis2web and can not be exported  by Qgis2web. So this issue is Qgis2web issue it seems ...

My use case should be very simple i use maptiler to have some topo layers in qgis and after i just export for use with openlayer ...

**Comment by lazaa32** [comment]
Hi @jipexu 
you can edit the Topo map at MapTiler Cloud. Disabled/enabled any layers you need (so you can keep just contour lines) and then you can publish it and easily export into mapbox, leaflet or openlayers.
