### ISSUE TITLE
copyright decoration does not cancel that of other projects

### ISSUE THREAD

**Issue by pigreco** [maptiler/qgis-maptiler-plugin#129]
the MapTiler plugin adds the copyright decoration and that's a great thing, but if I use a decoration in another project, this decoration always matches the one created by the plugin:

## QGIS just started and new project, I add a background map with QMS (quickMapServices plugin)

![image](https://user-images.githubusercontent.com/7631137/90317182-d34d5280-df27-11ea-9796-5b0890f2c143.png)

## I close the project (without exiting QGIS) and I open the project with decoration

![image](https://user-images.githubusercontent.com/7631137/90317205-f841c580-df27-11ea-9ea3-2529cc4a0d43.png)

## I close the project (without exiting QGIS) and add OpenStreetMap, I find the union of two decorations:

![image](https://user-images.githubusercontent.com/7631137/90317272-6be3d280-df28-11ea-89db-f0f2ba1674f3.png)

## SO

![image](https://user-images.githubusercontent.com/7631137/90317286-8b7afb00-df28-11ea-9e39-319050b59429.png)

**Comment by lazaa32** [comment]
Hi @pigreco ,

I can't replicate your issue with decorators. I am also bit confused as it looks that none of the maps in your pictures is added via MapTiler. Could you please write me a series of steps to replicate your problem? Thanks.

**Comment by pigreco** [comment]
@lazaa32 

Installing the Map Tiles plugin the problem manifests itself, even using background maps other than those of the plugin.

How to reproduce it:

1. start QGIS 3.14.15;
2. create a new project;
3. insert a simple copyright decoration, eg: W QGIS;
4. Close QGIS;
5. Restart QGIS and open the newly created project;
6. add any basemap using the MapTiles plugin,
the decoration will be added together with the previous one;

also, if we created a new project and added a background map from the MapTiles plugin, the decoration would always feature W QGIS.

As if the settings of the decorations remain memorized.

Video demo:
https://youtu.be/ivAKwIRR_mk
