### ISSUE TITLE
Min Zoom level above 14

### ISSUE THREAD

**Issue by Jnb2387** [maptiler/qgis-maptiler-plugin#131]
Great plugin!
I could never really understand the zoom levels with vector tiles in qgis and I can not get the Min. Zoom to honor anything past 14. For example I use openmaptiles data and for housenumbers I set to min zoom of 17 but they never appear in any zoom and it seems the only way is to set no min zoom or 14 or below.  I am using qgis 3.14.1 on linux mint 19.3.

**Comment by lazaa32** [comment]
Hi @Jnb2387 
Could you please specify the source of the vector tiles? Do you use a custom style.json?

**Comment by Jnb2387** [comment]
I have this issue with any style including the MapTiler default styles like Basic. For example if I change the road_major_label to have a Min. Zoom of 15 (or anything > 14) the roads never show at any zoom level.
