### ISSUE TITLE
QGIS crashes whenever maptiler plugin is used

### ISSUE THREAD

**Issue by tabell** [maptiler/qgis-maptiler-plugin#134]
OS: Fedora 32, Linux kernel 5.7.16, 
QGIS Version: QGIS 3.14.16-Pi 'Pi' (exported), installed via dnf from https://copr.fedorainfracloud.org/coprs/dani/qgis/
Maptiler installed from plugin manager

Action: Right click Maptiler entry in Browser, from context menu, select 'Account...'
Expected: Settings dialog opens with space to enter API key
Actual: QGIS exits immediately
Note: Attempting to insert a maptiler layer brings up the dialog saying: Access error occured, please set up your API key, and then exits when I click Ok

Running QGIS from the command line and then following the steps above produces this output

[qgis_crash.txt](https://github.com/maptiler/qgis-maptiler-plugin/files/5250955/qgis_crash.txt)

**Comment by rduivenvoorde** [comment]
@tabell tried to reproduce this (I had 3.14.15 here...) but had no crash.

Then I compiled the new 3.14.16 and there I can reproduce the crash there.

Note that in current Master/Main (upcoming 3.16) I have NO crash....
