### ISSUE TITLE
Plugin does not take QGIS Proxy Settings into Account

### ISSUE THREAD

**Issue by sebastian-r-schmidt** [maptiler/qgis-maptiler-plugin#136]
In my company we're sitting behind a http proxy server. Requests to MapTiler API are timing out.  So unfortunately I cannot use it in the company context (which would of course need the appropriate MapTiler licences, I'm currently just testing out the options).

 A quick look into the code revealed that this plugin is not using QGIS' standard network access tools which would route all requests through the proxy settings which are defined by QGIS systemwide. Instead the python library reqeusts is used directly. 
Any chance to change that in a future release? The usage of QGSNetworkAccessManager would be the way to go AFAIK.

**Comment by lazaa32** [comment]
Hi @sebastian-r-schmidt 
we know about the issue #80 but so far there wasn't enough capacity to fix it and there was't any bug report until now. I will add it to the next milestone. I plan to make a new release this month with this issue included.

**Comment by lazaa32** [comment]
We can test it with SSHSockProxy
```
ssh -D 1337 -q -C -N user@ma.ttias.be
```

**Comment by lazaa32** [comment]
Fixed in #159. Requests are now done using QgsNetworkAccessManager class.
