### ISSUE TITLE
Vector tiles: Label font size too small on hdpi screen

### ISSUE THREAD

**Issue by JeremyG** [maptiler/qgis-maptiler-plugin#137]
(First of all thanks for this amazing plugin, especially for the vector tiles!)

I'm having a font size issue here on my 13'' HP Spectre (3840 x 2160 px resolution): it's way too small and I can barely read the names. Here over Paris:

![Capture d’écran 2020-10-04 183946](https://user-images.githubusercontent.com/3398608/95021497-97a24f80-0671-11eb-9e07-e8a456fcfcf4.png)

In comparison, on this image, QGIS interface font is Ubuntu and is set to 10 pts.

Maybe I missed a config option somewhere?

**Comment by lazaa32** [comment]
Hi @JeremyG 
you can try to open Layer Styling Panel (F7 shortcut) and click on the Labels tab. Here you can modify labels setting for any layer. I would suggest you to try change size unit from Pixel to Points or vice versa as I know that might cause some issues on HighRes displayes. If not, just change the size of labels.

**Comment by JeremyG** [comment]
Hi @lazaa32, thanks for your input. It works way better indeed with Points instead of Pixels on every layer:

![Capture d’écran du 2020-10-06 11-10-18](https://user-images.githubusercontent.com/3398608/95182283-b1a07700-07c4-11eb-8b8d-5c0e04c8b11a.png)

![Capture d’écran du 2020-10-06 11-11-40](https://user-images.githubusercontent.com/3398608/95182295-b533fe00-07c4-11eb-93ce-40810fdb61c5.png)

However the process is a bit tedious as I have to change the setting layer after layer. Is there a way to make this permanent?

**Comment by lazaa32** [comment]
Unfortunately not at the moment.

**Comment by JeremyG** [comment]
I just figured I could save it as a layer definition file (.qlr) and open it after through the Explorer. It's a convenient enough workaround.

**Comment by lazaa32** [comment]
I didn't think of that. Thanks for the workaround!
