### ISSUE TITLE
Contour labels are not shown at any zoom level

### ISSUE THREAD

**Issue by tabell** [maptiler/qgis-maptiler-plugin#139]
QGis 3.16.0-1, Arch Linux, MapTiler plugin 1.1.3

Steps to reproduce:
1. Open QGis
2. Add a new MapTiler topographic map

Expected:
Contour lines show labels at any zoom level

Actual:
No contour labels appear at any zoom level

**Comment by lazaa32** [comment]
Hi @tabell 
did you add MapTiler `Topographique` map? I just tested it and I can see the countour lines just fine. They have defined minzoom in tiles.json to value 9. But at this zoom I can see them. Tested on QGIS 3.16.0, MapTiler plugin 1.1.3, Ubuntu 20.04

![image](https://user-images.githubusercontent.com/19833762/99045525-c75a4680-2591-11eb-9678-0969462c91ca.png)

**Comment by francis33** [comment]
QGIS 3.16-2, Windows 10, plugin 1.1.3

Same problem. Unable to solve it.
It's only for vector map.

Can you help ?

Best
Francis
