### ISSUE TITLE
New connection modal window

### ISSUE THREAD

**Issue by lazaa32** [maptiler/qgis-maptiler-plugin#14]
After clicking on `Add new connection` menu item a modal window appears. SizePolicy for labels looks either hardcoded or not optimized. Label `Map Name` isn't displayed entirely.

![new_connection](https://user-images.githubusercontent.com/19833762/82349100-fdab7480-99f9-11ea-8c08-ab5efc6a4cde.png)

Btw, the menu item `Add new connection` should be `Add new connection...` imho according to UX [conventions](https://medium.com/@jsaito/the-mighty-ellipsis-6c2c00ddc864).

**Comment by klokan** [comment]
This dialog should look better - give people guidance what they are suppose to copy&paste and from where...

Related to #8 - or even a duplicate?

**Comment by lazaa32** [comment]
Also there should be an error message if you try to add new map that already exists in User Maps group. Right now there is only print message in Python console: `Landcover already exist, input other name.` but no visual error message for user at GUI.

**Comment by lazaa32** [comment]
TextField for URL is not long enough so when copying a long URL it might be trimmed.
