### ISSUE TITLE
error loading sprites apple silicon

### ISSUE THREAD

**Issue by amorfinv** [maptiler/qgis-maptiler-plugin#147]
I wasn't able to load sprites into QGIS.

I tried ` /Applications/QGIS.app/Contents/MacOS/bin/pip3 install pillow -U`. but it did not seem to work in a terminal window with Rosetta2.

I get the following error:

```
ERROR: Command errored out with exit status 1: /Applications/QGIS.app/Contents/MacOS/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/wp/vn2yyjjj3lx1_29z1qrqtdlw0000gn/T/pip-install-fsvqhxv3/pillow/setup.py'"'"'; __file__='"'"'/private/var/folders/wp/vn2yyjjj3lx1_29z1qrqtdlw0000gn/T/pip-install-fsvqhxv3/pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/wp/vn2yyjjj3lx1_29z1qrqtdlw0000gn/T/pip-record-ihpqd0o4/install-record.txt --single-version-externally-managed --compile --install-headers /Applications/QGIS.app/Contents/MacOS/include/python3.8/pillow Check the logs for full command output.
```

It is quite long so I only copied the last part. Let me know if I should copy the whole error. I guess it must be an ARM issue.

**Comment by lazaa32** [comment]
Hi @amorfinv,
This plugin wasn't tested with Apple silicon and Rosetta and I have never run into this issue. Could you please paste complete log? Also what is your current version of pillow?

**Comment by amorfinv** [comment]
Hello @lazaa32.

So when I double click the style "Bright" The following message appears (see image).

`You do not have PIL/Pillow library installed on your system. Sprites will not be supported.
MacOS users: To install Pillow library, run following code in terminal:
/Applications/QGIS.app/Contents/MacOS/bin/pip3 install pillow -U`

![Screen Shot 2021-05-03 at 11 32 03 AM](https://user-images.githubusercontent.com/78442543/116861454-67209500-ac03-11eb-8eb4-95983204fe89.png)

I currently have pillow version 8.2.0 installed but I guess qgis is not finding it?

This is the [log](https://github.com/maptiler/qgis-maptiler-plugin/files/6414089/log.txt) from running `/Applications/QGIS.app/Contents/MacOS/bin/pip3 install pillow -U` in a rosetta terminal.

**Comment by lazaa32** [comment]
Hi @amorfinv ,

I am not a mac user, but we had a similar issue with pillow at MacOS (see #140). QGIS needs to have installed its own Pillow. I would  try to uninstall your current version of Pillow and then run:
```
/Applications/QGIS.app/Contents/MacOS/bin/pip3 install --upgrade pip
/Applications/QGIS.app/Contents/MacOS/bin/pip3 install --upgrade Pillow
```
I'm not sure whether that help though.
What is your version of QGIS?
Please also note, that some map styles don't use sprites, so even though you get this error message, you should be able to display maps via MapTiler plugin (e.g. Basic).

**Comment by amorfinv** [comment]
Thanks for the help @lazaa32.

I have the latest version: QGIS 3.18.2 'Zürich'.

That did the trick. Error is no longer popping up and maps seem to be rendering fine.

-Andres
