### ISSUE TITLE
Always crashing when adding à layer in QGIS 3.10.10

### ISSUE THREAD

**Issue by AdrienTaccoen** [maptiler/qgis-maptiler-plugin#148]
Hello,

Whenever I try to add a layer from the MapTiler plugin in QGIS 3.10.10, it freezes.

After ~30s to 1min, I get an error message (see attached txt file)

[maptiler_issue.txt](https://github.com/maptiler/qgis-maptiler-plugin/files/6421252/maptiler_issue.txt)

**Comment by lazaa32** [comment]
Hi @AdrienTaccoen 
it looks like a connection issue. Do you have valid API-key? Are you behind a proxy? Could you also provide version information from QGIS/Help/About menu?

**Comment by lazaa32** [comment]
Closing now. Feel free to re-open with additional information required for debugging.
