### ISSUE TITLE
maptilerをレイヤーとして読み込んでいないプロジェクト

### ISSUE THREAD

**Issue by gaihan** [maptiler/qgis-maptiler-plugin#149]
maptilerをレイヤーとして読み込んでいないプロジェクトでもマップビューに「C　MIERUNE　C　maptiler」とクレジットされますがなぜでしょう？
最初は「地図を画像としてエクスポート」した画像にクレジットが入り気付いたのですが、今は表示したマップビューに入っています。
[他のプロジェクトにはmaptilerをレイヤーとして読み込んだものもありますが、添付した画像のプロジェクトには読み込んでいません。
![maptilerクレジット](https://user-images.githubusercontent.com/86038420/122336348-a4ed3900-cf77-11eb-8007-3b1d1b1f4bc0.jpg)

QGISバージョン3.16.7　win10です。

**Comment by lazaa32** [comment]
Hi @gaihan, unfortunately, your comment is not readable for me, could you describe your problem again?

**Comment by gaihan** [comment]
Thank you AdamLaza
The Question is
Once I used layer Maptiler in QGIS, I see the credit called "Maptiler" at
the bottom right of the screen, even for projects that do not use
Maptiler.Is there a way to get rid of this.

2022年2月17日(木) 5:18 Adam Laža ***@***.***>:

**Comment by lazaa32** [comment]
Duplicate of #129
