### ISSUE TITLE
Vector tiles: Style could not be completely converted

### ISSUE THREAD

**Issue by shoetten** [maptiler/qgis-maptiler-plugin#151]
When trying to load MapTiler vector tiles into a new QGIS project, no labels are displayed on the map.

The Details view shows errors like

```
label_airport: Could not convert expressions in layer style definition, check Python console for details.
label_road: Could not convert expressions in layer style definition, check Python console for details.
label_place_other: Could not convert expressions in layer style definition, check Python console for details.
label_place_city: Could not convert expressions in layer style definition, check Python console for details.
label_country_other: Could not convert expressions in layer style definition, check Python console for details.
label_country: Could not convert expressions in layer style definition, check Python console for details
```

while the python console is also not much more informative, continuously printing out

```
'float' object cannot be interpreted as an integer
# or
split() requires a non-empty pattern match.
```

QGIS Version: both `3.22.2` (with Python 3.10.1 under Arch Linux) and `3.16.3` (with Python 3.6.9 under Ubuntu 18.04)
MapTiler Plugin Version: `2.0.0`

Unfortunately, without any knowledge of the plugin and no line number, i'm not able to debug this myself. Hope someone can help!

**Comment by lazaa32** [comment]
Hi @shoetten,

could you please provide URL link to style.json and version of MapTiler plugin?

**Comment by shoetten** [comment]
Sure. I'm using MapTiler plugin `2.0.0` and the provided styles (e.g. Basic, Bright, Outdoor, etc).

**Comment by lazaa32** [comment]
I cannot replicate that with QGIS 3.22.0 and plugin 2.0, but as there are errors related to `label_*` layers I would guess it might be related to fonts installed on your system. The error message in Python console is not very descriptive - it should be improved.

Could you please check whether you have `Noto Sans` family fonts installed on your system? Then try to add Basic again and let me know if there are still any error messages.

**Comment by shoetten** [comment]
That was my first guess, as well, but unfortunately, it didn't help.. I have Noto Sans installed (in 72 different variantions, acutally ;)).

**Comment by lazaa32** [comment]
Hi @shoetten,
does your issue with labels persist? Would you be willing to test another version of the plugin? I did some modifications to font style parsing and added few debug messages.
Could you please:
1. Uninstall current version from QGIS/Plugins/Manage and install plugins.../MapTiler Plugin/Uninstall plugin
2. Download new version from here: [qgis-maptiler-plugin.zip](https://github.com/maptiler/qgis-maptiler-plugin/files/8038934/qgis-maptiler-plugin.zip)
3. Install plugin from ZIP QGIS/Plugins/Manage and install plugins.../Install from ZIP/Choose downloaded zip file.
4. Test any map and copy&paste here any Warnings or Error/Debug messages from Python console if any.
Thank you for your help.

**Comment by shoetten** [comment]
Unfortunately, the errors still persist, although with a new debug message :+1: 

```
Debug split_font_family: Noto Sans Italic
'float' object cannot be interpreted as an integer
[...]
Debug split_font_family: Noto Sans Regular
'float' object cannot be interpreted as an integer
[...]
Debug split_font_family: Noto Sans Bold
'float' object cannot be interpreted as an integer
[...]
```

**Comment by lazaa32** [comment]
Hi @shoetten
I added the whole traceback into debug message, which should help localize the error since I can't duplicate it on my computer.
Could you please test the plugin one more time, this time with this version, please? 
[qgis-maptiler-plugin.zip](https://github.com/maptiler/qgis-maptiler-plugin/files/8058478/qgis-maptiler-plugin.zip)
Thank you for your help.

**Comment by kertase** [comment]
I have the same issue, I tried the zip and I get:
```
'float' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/gl2qgis/gl2qgis.py", line 82, in parse_layers
    has_renderer_style, renderer_style, has_labeling_style, labeling_style = parse_symbol_layer(json_layer, context)
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/gl2qgis/gl2qgis.py", line 751, in parse_symbol_layer
    label_settings.autoWrapLength = text_max_width
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by lazaa32** [comment]
Hi @kertase,
thanks, I fix this line, can you please try again?
[qgis-maptiler-plugin.zip](https://github.com/maptiler/qgis-maptiler-plugin/files/8069256/qgis-maptiler-plugin.zip)
Could you please also provide your version of QGIS, Python and OS? I am really curious why it works for me and not for you...

**Comment by kertase** [comment]
I get new errors now: 

´´´
'float' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/gl2qgis/gl2qgis.py", line 82, in parse_layers
    has_renderer_style, renderer_style, has_labeling_style, labeling_style = parse_symbol_layer(json_layer, context)
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/gl2qgis/gl2qgis.py", line 944, in parse_symbol_layer
    label_settings.priority = min(text_size / (context.pixelSizeConversionFactor() * 3), 10.0)
TypeError: 'float' object cannot be interpreted as an integer
’’’

My system info:

´´´
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>


QGIS version | 3.22.3-Białowieża | QGIS code branch | Release 3.22
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.10.1
GDAL/OGR version | 3.4.0
PROJ version | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 13.4
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.1
OS version | Arch Linux
  |   |   |  
Active Python plugins
FreehandRasterGeoreferencer | 0.8.3
QuickWKT | 3.1
DigitizingTools | 1.5.1
shapetools | 3.4.2
mapbiomascollection | 1.4
db_manager | 0.1.20
processing | 2.12.99
grassprovider | 2.12.99
sagaprovider | 2.12.99
qgis-maptiler-plugin | 2.0.0

</body></html>QGIS version
3.22.3-Białowieża
QGIS code branch
[Release 3.22](https://github.com/qgis/QGIS/tree/release-3_22)
Qt version
5.15.2
Python version
3.10.1
GDAL/OGR version
3.4.0
PROJ version
8.2.0
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
13.4
SpatiaLite version
5.0.1
QWT version
6.2.0
QScintilla2 version
2.13.1
OS version
Arch Linux

´´´

**Comment by lazaa32** [comment]
Thanks @kertase,
I have a bit older versions, not sure that's the problem.
I went through the code and cast float to int on the problematic lines. Could you test one more time? (Hopefuly for the last time, I don't like this kind of remote debugging).
[qgis-maptiler-plugin.zip](https://github.com/maptiler/qgis-maptiler-plugin/files/8080660/qgis-maptiler-plugin.zip)

**Comment by kertase** [comment]
It works perfect now for me :)

**Comment by shoetten** [comment]
yes :tada: same for me.
