### ISSUE TITLE
Plugin keeps asking for API-key

### ISSUE THREAD

**Issue by geomenke** [maptiler/qgis-maptiler-plugin#152]
The plugin keeps asking for the API-key even though it has been entered. I have tried replacing the key several times but it will not accept the key.

**Comment by lazaa32** [comment]
Hi @geomenke could you please provide more details?
Please follow these steps:
1. Go to QGIS/Help/About, copy the text field from About tab and paste it here
2. Go to Browser/Vector Tiles/Right click/New generic connection...
3. Create new connection MapTiler Planet with URL: `https://api.maptiler.com/tiles/v3/{z}/{x}/{y}.pbf?key=` and insert your key at the end of URL 
![image](https://user-images.githubusercontent.com/19833762/151171912-6aa187f2-e669-4be2-abb1-666c6998471a.png)
4. Open Debugging/Development tools (press F12)
5. Click on MapTiler Planet under Vector tiles and copy/paste here the information from Debug tool
![image](https://user-images.githubusercontent.com/19833762/151172446-621ece9e-1415-4cff-826f-f914b79309a0.png)

**Comment by geomenke** [comment]
It is working now so I am going to close this.
