### ISSUE TITLE
Issue with zoom level - Service Track

### ISSUE THREAD

**Issue by charles9469** [maptiler/qgis-maptiler-plugin#167]
Hello,

I wan't to display Service track at every zoom level using the Topo Map.

Unfortunatly, I cannot change the value in order to solve this problem.

Is that possible ? Or is it control and the root of your map ??

Thank you
Charles, France.

![image](https://user-images.githubusercontent.com/8075710/157460560-3c750950-b3ba-42c0-b536-bdb5550c5786.png)

**Comment by lazaa32** [comment]
Hi @charles9469,

it is not possible to display them on every zoom level. Roads of class `service` (raw data encoded in vector tiles) are only in tiles of zoom levels 13 and 14. Thus, it is not possible to render service roads before this zoom level.

**Comment by lazaa32** [comment]
OMT schema related. Closing now.
