### ISSUE TITLE
Keps asking for API-key

### ISSUE THREAD

**Issue by blosky** [maptiler/qgis-maptiler-plugin#172]
When I try to use any map on the QGIS plugin keeps asking for API-key even though I have tried with several

**Comment by lazaa32** [comment]
Hi @blosky 
could you please open QGIS and in the top menu go to Help/About and copy/paste here the information about your versions installed? Especially, QGIS, Qt, Python and qgis-maptiler-plugin versions.
Also what API keys did you use?

**Comment by lazaa32** [comment]
Closing now. Feel free to re-open with additional information required for debugging.
