### ISSUE TITLE
SSL Error for vector tiles that require sprite.json

### ISSUE THREAD

**Issue by maxsitt** [maptiler/qgis-maptiler-plugin#173]
When trying to load certain maps (e.g. OpenStreetMap, Streets) as vector tiles, the following error is shown in QGIS:

An error has occurred while executing Python code: 
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.maptiler.com', port=443): Max retries exceeded with url: /maps/openstreetmap/sprite.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

The same maps can be loaded as raster tiles without problem. It seems like only vector tiles that require the sprite.json labeling information can not be loaded into QGIS (at the moment).

QGIS version: 3.24.2-Tisler
MapTiler Plugin version: 3.0.3
Python version: 3.9.5

**Comment by lazaa32** [comment]
Hi @maxsitt 
Never run into this error. Could you please test it in a new project with a new User profile (QGIS/Settings/User profiles/New profile..). You will have to install the plugin again.
Please let me know whether you are able to load Basic, Streets, OpenStreetMap and Bright.
If the problem still occurs, could you please delete all maps from the Layer panel, then open Debugging/Network tools (F12 or View/Panels/Debugging and Developers tools) and then load e.g. Streets again. You should see network requests in the panel similar to this image. There should be a request for sprite.json probably emphasized in red with some error. Please, paste here a screenshot or copy the error message in the response.
![image](https://user-images.githubusercontent.com/19833762/166518328-3313204b-7e28-4127-81fb-00e14f51bb48.png)

**Comment by maxsitt** [comment]
Thanks for your quick response @lazaa32 !

I followed your instructions, but the same error is still occuring for Streets, OpenStreetMap and Bright. Basic works fine, also as vector tiles.

There is no request for the sprite.json:
![Screenshot (94)](https://user-images.githubusercontent.com/87697856/166643786-e6d42523-b6db-4aae-8fef-dcaad99b72b2.png)

I'm behind a company proxy, but this is activated in QGIS settings and everything else (also other plugins) works fine.

More from the error message:

2022-05-04T10:05:53    WARNING    Traceback (most recent call last):

              File "C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
              httplib_response = self._make_request(
              File "C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
              self._validate_conn(conn)
              File "C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
              conn.connect()
              File "C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\urllib3\connection.py", line 362, in connect
              self.sock = ssl_wrap_socket(
              File "C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\urllib3\util\ssl_.py", line 386, in ssl_wrap_socket
              return context.wrap_socket(sock, server_hostname=server_hostname)
              File "C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\ssl.py", line 500, in wrap_socket
              return self.sslsocket_class._create(
              File "C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\ssl.py", line 1040, in _create
              self.do_handshake()
              File "C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\ssl.py", line 1309, in do_handshake
              self._sslobj.do_handshake()
             ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\requests\adapters.py", line 439, in send
              resp = conn.urlopen(
              File "C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
              retries = retries.increment(
              File "C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\urllib3\util\retry.py", line 446, in increment
              raise MaxRetryError(_pool, url, error or ResponseError(cause))
             urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.maptiler.com', port=443): Max retries exceeded with url: /maps/streets/sprite.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))`

**Comment by lazaa32** [comment]
Hi @maxsitt,
it seems to me it is proxy-related but I just tested it and it works for me even behind a proxy.
I asked our Cloud guys whether they have an idea.
Could you please test one more thing:
Add e.g. OpenStreetMap directly via QGIS with these steps:
1) Get your API-key at https://cloud.maptiler.com/account/keys/
2) In QGIS Go to Browser Panel/Vector tiles/New generic connection... and add connection to OpenStreetMap manually with your API key
- Name: OpenStreetMap
- URL: https://api.maptiler.com/tiles/v3-openmaptiles/{z}/{x}/{y}.pbf?key=*YOUR_KEY*
- Style URL: https://api.maptiler.com/maps/openstreetmap/style.json?key=*YOUR_KEY*
![image](https://user-images.githubusercontent.com/19833762/166673657-cf632664-588d-4b32-955f-ac0a9c9b2879.png)
3) Save the connection and then add it to canvas. 

You will get some warnings and the map will have some layers not styled properly but I am curious whether you get the same Python error and whether the request for the sprite.json fails again.
![image](https://user-images.githubusercontent.com/19833762/166674435-fa0c8154-138f-4a51-9ef1-c60277eddbf7.png)

**Comment by maxsitt** [comment]
This approach is working fine! No python error and the sprite.json request is sucessful:
![Screenshot (95)](https://user-images.githubusercontent.com/87697856/166686819-3e0e5112-9c68-4d5c-b758-572bde5c9ec9.png)

BTW, as you can see at the bottom of the map, I have a similar problem to #149 and #129 regarding the copyright decoration.

**Comment by lazaa32** [comment]
Ok, thanks for your report. I will take a look at it. I know about the copyright issues, I will try to fix it once I find some time for that :( 

If you are not happy with the broken style layers, the only workaround I can suggest to you is to modify style.json.
1. Save style.json for the map you want to display in QGIS e.g. https://api.maptiler.com/maps/streets/style.json?key=*YOURKEY*
2. Find this line in style.json and remove it
```
  "sprite": "https://api.maptiler.com/maps/streets/sprite",
```
3. Go to MapTiler Cloud/Maps click on New Map menu/Upload map
4. Fill up the form with a custom name and choose modified style.json
5. Create Map style, then on Publish
6. On the Map style detail page, copy the link to style.json under the Use vector style section
7. In QGIS, right-click on MapTiler plugin/Add a new map.../From URL
8. Insert name and paste the link to style.json
9. Add map to canvas - you will get some symbol warnings because of missing sprite.json but other layers should be displayed fine.

**Comment by maxsitt** [comment]
I will try that, thanks for the great support!
