### ISSUE TITLE
Can this plugin be used programatically?

### ISSUE THREAD

**Issue by adamakhtar** [maptiler/qgis-maptiler-plugin#178]
Hi,

I'm exploring options to programmatically print out maps and I came across this plugin via Google.  

From the screenshots it seems it has to be used via the QGIS desktop application. I have zero experience with QGIS but looking through QGIS's documentation it seems some [scripting is possible with it](https://docs.qgis.org/3.22/en/docs/pyqgis_developer_cookbook/composer.html).

Is it also possible to use this plugin in scripts?

**Comment by lazaa32** [comment]
Hi @adamakhtar ,
it is possible to use this plugin via PyQGIS however it requires some experience. Please also note, that this plugin is not meant for printing but for styling vector tiles.

**Comment by adamakhtar** [comment]
@lazaa32 thanks for the info. 

> Please also note, that this plugin is not meant for printing but for styling vector tiles.

I'm a bit confused now because this MapTiler blog post suggests it is possible https://documentation.maptiler.com/hc/en-us/articles/4408609607825-How-to-print-and-show-vector-tiles-in-QGIS-via-MapTiler-plugin 

> Do you need fully customizable base maps for QGIS? Do you need to **print** a map that you created in MapTiler Cloud? After reading this article you will know how to do it via the MapTiler plugin.

Is it no longer possible?

To be clear I have my own vector tile server with my own mapbox style.json and I'd like to produce hi-res DPI images. Is this not possible?

**Comment by lazaa32** [comment]
@adamakhtar 
sorry, if I was not clear: the MapTiler plugin itself is not meant for printing (it does not implement any printing functionality). You can use the plugin to style vector tiles and then use the QGIS to print them (even programmatically).

So you can add your own style.json and display styled tiles from your tile server via this plugin. If you want to print it, it is possible but printing is done via QGIS Print Layout.
