### ISSUE TITLE
Vector tiles: Style could not be completely converted on QGIS 3.34.4-Prizren

### ISSUE THREAD

**Issue by Dret42** [maptiler/qgis-maptiler-plugin#188]
Hi to all, 
I receive this message when loading some Map Tile maps (es. Bright, Openstreetmap). In the error details this is highlighted:

The following warnings were generated while converting the vector tile style:

_Campsite: Skipping unsupported expression.
Zoo: None of fonts in ['Open Sans Bold', 'Noto Sans Bold'] is available on your system. Default font will be used.
Train: None of fonts in ['Open Sans Bold', 'Noto Sans Bold'] is available on your system. Default font will be used.
Zoo: Skipping unsupported expression.
Ferry labels: None of fonts in ['Open Sans Regular', 'Noto Sans Regular'] is available on your system. Default font will be used.
Ferry labels: Skipping unsupported expression.
Food: None of fonts in ['Open Sans Semibold', 'Noto Sans Bold'] is available on your system. Default font will be used.
Cultural: Skipping unsupported expression.
Outdoor: Skipping unsupported expression.
Ferry: Skipping unsupported expression.
Bus stop: None of fonts in ['Open Sans Regular', 'Noto Sans Regular'] is available on your system. Default font will be used.
Primary road shield: None of fonts in ['Noto Sans Regular'] is available on your system. Default font will be used.
Mall: Skipping unsupported expression.
Mountain peak labels: None of fonts in ['Open Sans Regular', 'Noto Sans Regular'] is available on your system. Default font will be used.
Capital city labels: None of fonts in ['Open Sans Semibold', 'Noto Sans Regular'] is available on your system. Default font will be used.
River labels: Skipping unsupported expression.
City labels: Skipping unsupported expression.
Airport gate labels: None of fonts in ['Open Sans Semibold', 'Noto Sans Regular'] is available on your system. Default font will be used.
Attraction: Skipping unsupported expression.
Airport labels: None of fonts in ['Open Sans Italic', 'Noto Sans Italic'] is available on your system. Default font will be used.
Education: Skipping unsupported expression.
Bus stop: Skipping unsupported expression.
National park labels: None of fonts in ['Open Sans Semibold Italic', 'Noto Sans Italic'] is available on your system. Default font will be used.
Other labels: None of fonts in ['Open Sans Semibold', 'Noto Sans Regular'] is available on your system. Default font will be used.
Town labels: Skipping unsupported expression.
Waste: None of fonts in ['Open Sans Semibold', 'Noto Sans Bold'] is available on your system. Default font will be used.
Secondary road shield: None of fonts in ['Noto Sans Regular'] is available on your system. Default font will be used.
Ocean labels: None of fonts in ['Open Sans Regular', 'Open Sans Light'] is available on your system. Default font will be used.
Bus station: None of fonts in ['Open Sans Bold', 'Noto Sans Bold'] is available on your system. Default font will be used.
Town labels: None of fonts in ['Open Sans Semibold', 'Noto Sans Regular'] is available on your system. Default font will be used.
Mortuary: None of fonts in ['Open Sans Bold Italic', 'Noto Sans Regular'] is available on your system. Default font will be used.
Outdoor: None of fonts in ['Open Sans Semibold', 'Noto Sans Bold'] is available on your system. Default font will be used.
Airport labels: Skipping unsupported expression.
State labels: Skipping unsupported expression.
Health: Skipping unsupported expression.
Road labels: Skipping unsupported expression.
Major airport labels: None of fonts in ['Open Sans Italic', 'Noto Sans Italic'] is available on your system. Default font will be used.
State labels: None of fonts in ['Open Sans Regular', 'Noto Sans Bold'] is available on your system. Default font will be used.
Country labels: None of fonts in ['Open Sans Semibold', 'Noto Sans Bold'] is available on your system. Default font will be used.
Bus station: Skipping unsupported expression.
House number labels: None of fonts in ['Noto Sans Regular'] is available on your system. Default font will be used.
Food: Skipping unsupported expression.
Shop: Skipping unsupported expression.
Car: Saltare l'espressione non supportata
Other labels: Skipping unsupported expression.
Local park: Skipping unsupported expression.
Shop: Saltare l'espressione non supportata
Attraction: None of fonts in ['Open Sans Semibold', 'Noto Sans Bold'] is available on your system. Default font will be used.
Local park: None of fonts in ['Open Sans Semibold Italic', 'Noto Sans Italic'] is available on your system. Default font will be used.
Village labels: None of fonts in ['Open Sans Semibold', 'Noto Sans Regular'] is available on your system. Default font will be used.
Ferry: None of fonts in ['Open Sans Regular', 'Noto Sans Regular'] is available on your system. Default font will be used.
Road labels: None of fonts in ['Open Sans Regular', 'Noto Sans Regular'] is available on your system. Default font will be used.
Accommodation: None of fonts in ['Open Sans Semibold', 'Noto Sans Bold'] is available on your system. Default font will be used.
National park labels: Skipping unsupported expression.
Lakeline labels: None of fonts in ['Open Sans Regular', 'Noto Sans Regular'] is available on your system. Default font will be used.
Cultural: None of fonts in ['Open Sans Semibold', 'Noto Sans Bold'] is available on your system. Default font will be used.
Public: None of fonts in ['Open Sans Semibold', 'Noto Sans Bold'] is available on your system. Default font will be used.
Car: None of fonts in ['Open Sans Semibold', 'Noto Sans Bold'] is available on your system. Default font will be used.
Harbor: Skipping unsupported expression.
City labels: None of fonts in ['Open Sans Semibold', 'Noto Sans Regular'] is available on your system. Default font will be used.
Health: None of fonts in ['Open Sans Regular', 'Noto Sans Regular'] is available on your system. Default font will be used.
Education: None of fonts in ['Open Sans Semibold Italic', 'Noto Sans Regular'] is available on your system. Default font will be used.
Tertiary road shield: None of fonts in ['Noto Sans Regular'] is available on your system. Default font will be used.
Sport: None of fonts in ['Open Sans Semibold Italic', 'Noto Sans Bold'] is available on your system. Default font will be used.
Mortuary: Skipping unsupported expression.
Health: Saltare l'espressione non supportata
Highway shield: None of fonts in ['Noto Sans Regular'] is available on your system. Default font will be used.
Lakeline labels: Skipping unsupported expression.
Place of worship: None of fonts in ['Open Sans Semibold', 'Noto Sans Bold'] is available on your system. Default font will be used.
Shop: None of fonts in ['Open Sans Semibold', 'Noto Sans Bold'] is available on your system. Default font will be used.
Landuse pattern: Could not convert expressions in layer style definition, check Python console for details.
Harbor: None of fonts in ['Open Sans Semibold Italic', 'Noto Sans Italic'] is available on your system. Default font will be used.
Sport: Skipping unsupported expression.
River labels: None of fonts in ['Open Sans Regular', 'Noto Sans Regular'] is available on your system. Default font will be used.
Campsite: None of fonts in ['Open Sans Semibold', 'Noto Sans Bold'] is available on your system. Default font will be used.
Public: Skipping unsupported expression.
Waste: Skipping unsupported expression.
Mall: None of fonts in ['Open Sans Semibold Italic', 'Noto Sans Italic'] is available on your system. Default font will be used.
Train: Skipping unsupported expression._

My system infos are:

QGIS version
3.34.4-Prizren
QGIS Code Review
decd43dc
Qt version
5.15.3
Python version
3.9.18
Gdal/ogr version
3.8.4
Proj version
9.3.1
Database version of the EPSG Registry
v10,098 (2023-11-24)
Geos version
3.12.1-CHAPTERS-1.18.1
Sqlite version
3.41.1
Pdal version
2.6.0
PostgreSQL client version
16.1
Spatialite version
5.1.0
Qwt version
6.1.6
Qscintilla2 version
2.13.4
So version
Windows 10 Version 2009

**Comment by lazaa32** [comment]
Hi @Dret42 are you at the latest plugin version 3.2?
It's normal to see these warnings. These maps are designed primarily for web cartography and not all style layers definition are possible to reproduce in QGIS.
However, I can see that most of the warnings are font-related. QGIS uses the fonts that are installed on your OS. Style has some font defined and if the font is not on your computer, the style will fallback to a default one with warning. If you want to get rid of these warnings you should install the font (in this case it's `Open Sans` and `Noto Sans`) and after restarting QGIS, you should not see these warnings.

**Comment by Dret42** [comment]
Yes, I'm using  the last plugin version.
I installed the font and most of the warning are now resolved.
Thanks!

**Comment by lazaa32** [comment]
Ok, great.
Some maps will always show few warnings, but others - e.g. Streets, Basic, Outdoor - should be fully converted into QGIS styling without any warnings.
Feel free to close the issue, if you're happy with the solution. Thanks.
