### ISSUE TITLE
Geocoding in toolbar

### ISSUE THREAD

**Issue by klokan** [maptiler/qgis-maptiler-plugin#2]
We can add the geocoding with autocomplete - to zoom the map in QGIS to the specified place.

API uses the same key. It is documented at: https://cloud.maptiler.com/geocoding/

User interface probably similar to:

![image](https://user-images.githubusercontent.com/59284/78751530-b51c8800-7972-11ea-803d-73d97dff36d9.png)
https://www.lutraconsulting.co.uk/projects/discovery/

**Comment by klokan** [comment]
To not be implemented now.

**Comment by Kanahiro** [comment]
The Geocoding feature has already implemented. Should be closed?

**Comment by klokan** [comment]
Thank you for the first implementation.
