### ISSUE TITLE
[Style]: Add styling for raster layers

### ISSUE THREAD

**Issue by lazaa32** [maptiler/qgis-maptiler-plugin#23]
Some maps contain both vector and raster layers.
We need add styling/rendering for raster layers based on tile.json.
E.g. Topo map.

Raster with correct rendering(grayscale?)
![raster1](https://user-images.githubusercontent.com/19833762/82735516-a4598300-9d22-11ea-8a4c-9bce5ae66e17.png)

No style/rendering defined.
![raster2](https://user-images.githubusercontent.com/19833762/82735518-a6234680-9d22-11ea-8bae-311f21b912b7.png)

**Comment by klokan** [comment]
These are RGBA terrain tiles. You would need to read them with an equation (perhaps VRT?) - and then style.

An alternative would be to TEMPORARILY replace the RGBA terrain with client-side rendering
https://cloud.maptiler.com/tiles/terrain-rgb/
https://www.maptiler.com/news/2019/03/rgb-encoded-elevation-data-in-maptiler-cloud/
in the Topo+Topographique style (or perhaps also any other style???) with the older-style hill-shading in direct rasters with some constant opacity: 
https://cloud.maptiler.com/tiles/hillshades/

**Comment by lazaa32** [comment]
Partially solved in #49.
Still needs to be solved for Topo map where is atm rgba tiles.
@daliborjanak  please let us know when you switch back to hillshade as suggested in a comment above by @klokan

**Comment by daliborjanak** [comment]
Updated. Topo now uses the only raster hillshade, rgb-terrain removed.

**Comment by lazaa32** [comment]
Thank you.

**Comment by lazaa32** [comment]
Closed in #85.
