### ISSUE TITLE
Replace the visual assets

### ISSUE THREAD

**Issue by klokan** [maptiler/qgis-maptiler-plugin#3]
MapTiler designer should provide the icons for interface according to the wireframes in the SVG of right size.

Similar to: https://github.com/qgis/QGIS/blob/master/images/themes/default/mIconGeonode.svg - so canvas size 24x24px.

Also the logotype of the MapTiler in Dark and White mode as SVG (for pixels roughly of the size of the screen - so SVG canvas width 250px).

**Comment by klokan** [comment]
Assets are attached in .zip.

Figma preview: https://www.figma.com/file/RebNzfljcUcCteRoi5PPvE/SVG-icons-for-MapTiler-QGIS-Plugin?node-id=0%3A1
[icons for MapTiler QGIS Plugin-20200511T132714Z-001.zip](https://github.com/maptiler/qgis-maptiler-plugin/files/4609854/icons.for.MapTiler.QGIS.Plugin-20200511T132714Z-001.zip)

**Comment by klokan** [comment]
Could you please integrate these, @Kanahiro?

**Comment by Kanahiro** [comment]
Ok, I'll do it!
