### ISSUE TITLE
Copyright decorator

### ISSUE THREAD

**Issue by klokan** [maptiler/qgis-maptiler-plugin#30]
To be legal - whenever the map is displayed and on any medium - we must show appropriate copyright.

QGIS only supports this with a copyright decorator. Let's implement it - and display the deduplicated copyright from TileJSON - as JavaScript viewers do.

**Comment by klokan** [comment]
https://gis.stackexchange.com/questions/264604/access-modify-qgis-copyright-decoration-through-python/265681

- follow-up on https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/issues/158

Perhaps helpful: 
https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/cheat_sheet.html#decorators

**Comment by Kanahiro** [comment]
> Perhaps helpful:
https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/cheat_sheet.html#decorators

I quoted this page, it was very helpful!

**Comment by Kanahiro** [comment]
https://gis.stackexchange.com/questions/264604/access-modify-qgis-copyright-decoration-through-python/265681

To fix the class to Project-wise one, I tried this way but don't correctly work... it is able to read and write entries regarding to a copyright decoration, but haven't find a method to apply current project yet.

**Comment by lazaa32** [comment]
After discussion with @wonder-sk, this should be a solution:
```
QgsProject.instance().writeEntry("CopyrightLabel", "/Label", "hura!!")
QgsProject.instance().writeEntry("CopyrightLabel", "/Enabled", True)
QMetaObject.invokeMethod(iface.mainWindow(), "projectReadDecorationItems") 
iface.mapCanvas().refresh()
```

To get label and if it is enabled:
```
label, _ = QgsProject.instance().readEntry("CopyrightLabel", "/Label")
enabled, _ = QgsProject.instance().readEntry("CopyrightLabel", "/Enabled")
```

**Comment by Kanahiro** [comment]
These codes perfectly work! Thank you very much @lazaa32 @wonder-sk .

**Comment by Kanahiro** [comment]
I've pushed some commit in #32 thanks to advises above.
