### ISSUE TITLE
Label size/ level of details - vector vs raster

### ISSUE THREAD

**Issue by lazaa32** [maptiler/qgis-maptiler-plugin#38]
Compare label size/ level of details on vector and raster map at same zoom:

Vector:
![image](https://user-images.githubusercontent.com/19833762/83256689-26c6c480-a1b3-11ea-999c-927814014cc3.png)

Raster:
![image](https://user-images.githubusercontent.com/19833762/83256706-35ad7700-a1b3-11ea-8ec2-e3649ebd37fc.png)

**Comment by klokan** [comment]
Open next to the QGIS the same map at https://www.maptiler.com/maps/.
This should be the main reference for size and look&feel.

**Comment by lazaa32** [comment]
Closed in #85.
