### ISSUE TITLE
[Bug] Fix adding raster maps

### ISSUE THREAD

**Issue by lazaa32** [maptiler/qgis-maptiler-plugin#47]
If there is already existing group of vector map in Layers list and user adds another raster map it is added into the group.
How to reproduce:
- Add any vector map.
- Add it to canvas.
- Select the vector layer.
- Add any raster map.
- Add raster map to canvas.

![groups](https://user-images.githubusercontent.com/19833762/83491729-80c8d200-a4b2-11ea-8057-953fedb7be05.png)

Added raster map should be displayed at the same level as Vector map group.

**Comment by klokan** [comment]
BTW the same is happening with geocoding results IMHO.

**Comment by Kanahiro** [comment]
In #54 , added a commit about a matter you mentioned.
