### ISSUE TITLE
[Geocoding] Add extent to geocoding

### ISSUE THREAD

**Issue by lazaa32** [maptiler/qgis-maptiler-plugin#48]
If there is an added feature from geocoding we want to zoom to the feature extent.
Use `bbox` property from Geocoding response:
See sample queries at https://cloud.maptiler.com/geocoding/

**Comment by klokan** [comment]
Another issue here to fix is that when I type "Zurich" - I see a suggestion in Japanese.
It should come in native language or in the language set by the QGIS.
