### ISSUE TITLE
[Styling] Raster opacity

### ISSUE THREAD

**Issue by lazaa32** [maptiler/qgis-maptiler-plugin#49]
If there is a raster map with defined opacity (e.g. hill-shading) we want to parse opacity in to qgis style.

**Comment by lazaa32** [comment]
Related to #23 (maybe even duplicate...)

**Comment by Kanahiro** [comment]
Now I'm trying to improve this issue and I've realized there is no API to set opacity by @zoom_level.
In vector layer, symbols can be styled with expression but raster renderer have no API like this. Do you have any idea?
