### ISSUE TITLE
Update the list of hard-coded styles

### ISSUE THREAD

**Issue by klokan** [maptiler/qgis-maptiler-plugin#5]
The list under "Maps" need to be updated to contain what is currently offered in MapTiler Cloud.

It s the list at
https://github.com/maptiler/qgis-maptiler-plugin/blob/master/browser_root.py#L42

**Comment by Kanahiro** [comment]
Now map datas is defined in following:
https://github.com/maptiler/qgis-maptiler-plugin/blob/master/browser_rastermaps.py#L30

**Comment by klokan** [comment]
@lazaa32 - could you please add (to both raster and vector maps lists) also the localized styles - with by default closed openable folders for the country-specific styles - such as "Czechia", "Japan", - according to the [wireframe](https://docs.google.com/presentation/d/1CQKYTI9Bi_goKVVQogeFT4e26EsvvAG7f_73McdsEAk/edit#slide=id.p)...

**Comment by lazaa32** [comment]
For both vector and raster maps added mockups and added localized folders.
![folder_local_datasets](https://user-images.githubusercontent.com/19833762/82682963-67bd5700-9c50-11ea-8e99-17c0bbc4bd1d.png)
