### ISSUE TITLE
[Styling] Curved labels

### ISSUE THREAD

**Issue by klokan** [maptiler/qgis-maptiler-plugin#51]
Should be possible:

> select the layer labeling settings tab and then select 'advanced' from here you can choose 'curved' labels which follow the contours of a line

according to
 
https://gis.stackexchange.com/questions/32877/creating-curved-labels-in-qgis
and
https://docs.google.com/document/d/1ogo958kIG7Hp4mrrrsJRgeNS4m0or9t05rI5FK4nDK8/edit?usp=sharing

**Comment by Kanahiro** [comment]
> according to
https://gis.stackexchange.com/questions/32877/creating-curved-labels-in-qgis
and
https://docs.google.com/document/d/1ogo958kIG7Hp4mrrrsJRgeNS4m0or9t05rI5FK4nDK8/edit?usp=sharing

These are methods regarding to not vector layers but simple line features, I think.
In case of line features, each line has attributes, name, length, width or so on, and QGIS can show their attributes as characters along lines.

However, lines in vector layers has no attributes to show characters and even if has them,  the latest build QGIS can't access them. Therefore these methods cannot be applied for vector tiles.

To fix this, parsing style.json is needed but this is not so easy that takes more time.

**Comment by lazaa32** [comment]
@daliborjanak @klokan Do we want to implement this in 1.0.0 milestone?

**Comment by daliborjanak** [comment]
This would be nice to have it in 1.0.0 but I think there is no time for that. We can start to work on if when all major problems and changes in the interface will be solved.

**Comment by lazaa32** [comment]
@Kanahiro Please, have a look at #69 and decide which feature you can implement in shorter time. We want to implement as many features as possible so if labels take more time we can postpone it.
