### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'attribution'

### ISSUE THREAD

**Issue by saberraz** [maptiler/qgis-maptiler-plugin#56]
```
An error has occurred while executing Python code: 

AttributeError: 'NoneType' object has no attribute 'attribution' 
Traceback (most recent call last):
  File "/home/saber/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/maptiler.py", line 158, in _write_copyright_entries
    copyrights_text = self._parse_copyrights()
  File "/home/saber/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-maptiler-plugin/maptiler.py", line 179, in _parse_copyrights
    attribution = l.layer().attribution()
AttributeError: 'NoneType' object has no attribute 'attribution'
```

**Comment by saberraz** [comment]
I am using the master branch from your plugin and QGIS master (Ubuntu 20.04).

**Comment by Kanahiro** [comment]
Could you tell me which layers are visible in your case?

**Comment by saberraz** [comment]
None...the error appears every time a layer is added to QGIS session:
![Peek 2020-06-03 08-42](https://user-images.githubusercontent.com/2649047/83609536-5a6c6a80-a576-11ea-9df0-195c766517b6.gif)

**Comment by lazaa32** [comment]
Merged into master. Could you please try with your project now? @saberraz

**Comment by saberraz** [comment]
Brilliant. I can confirm that error message no long appears. Thanks for your quick response.

**Comment by TigerEye22** [comment]
I'm getting the same issue but don't know how to do what is suggested. Can someone help?

**Comment by ahunanyamichael** [comment]
please how to i solve this problem

**Comment by lazaa32** [comment]
Hi @ahunanyamichael,
this is a closed issue. Could you please open a new one and describe there your issue there?
Go to QGIS/Help/About and please copy the information about your software versions here.
Describe steps how to reproduce the issue.
Add additional images or gifs.
Thank you.
