### ISSUE TITLE
[Style]Incorrect layer order

### ISSUE THREAD

**Issue by Kanahiro** [maptiler/qgis-maptiler-plugin#61]
"gl2qgis" parses style.json into QgsVectorTIlesLayer as if each source is always used by one layer, but as you know some layers can use same one source.
When a order of layers are like following example, the problem occurs.

- sources and layers
```
[sources]
sample_raster
sample_vector

[layers]
#layer_id: source
vector_layer1: sample_vector,
raster_layer: sample_raster,
vector_layer2: sample_vector
```

- parsing by gl2qgis
```
[QGIS layers]
sample_raster,
sample_vector
```

Although it is not able now to separate one source to some layers, layers should be ordered following.

```
[QGIS layers]
vector_layer1,
raster_layer,
vector_layer2
```

**Comment by lazaa32** [comment]
I can't think of a solution in QGIS right now. We can change order of layer sources but it's not quite that helpful.

**Comment by lazaa32** [comment]
I improved the code so now when parsing style.json order of layers is considered. We should still find out better solution...
E.g. Mierune Street style, source layer order and num of occurrence:
```
'jp_hillshade', 1x
'jp_mierune', 15x
'jp_gsi_building', 4x 
'jp_mierune', 66x,
'jp_forest' 1x
```
I used a rule of first occurence so the final order is:
```
'jp_hillshade'
'jp_mierune'
'jp_gsi_building'
'jp_forest'
```

We could also set the order based on number of occurence however it's not ideal either.

**Comment by lazaa32** [comment]
It is possible to change order of source layers. Order of style layers is defined in style.json. Possible work-around is to merge two source layers into one and then set the correct order in style.json.
