### ISSUE TITLE
Test plugin

### ISSUE THREAD

**Issue by lazaa32** [maptiler/qgis-maptiler-plugin#67]
We need to test our plugin.
QGIS 3.4 (latest LTR):
- test raster tiles
- test UI

QGIS 3.13+:
- test raster tiles
- test UI
- test vector tiles
- test styles

**Comment by lazaa32** [comment]
@daliborjanak I will let you know as soon as most of the desired feature for 1.0.0 will be implemented.

**Comment by daliborjanak** [comment]
QGIS 3.4 - tested, working correctly
