### ISSUE TITLE
[Styling] implement support for sprites

### ISSUE THREAD

**Issue by lazaa32** [maptiler/qgis-maptiler-plugin#69]
We would like to get implemented a support for sprites in maps.
Good map style to start with is Toner.

**Comment by Kanahiro** [comment]
I don't think it is possible for me to implement this by next Monday.

**Comment by lazaa32** [comment]
Ok, do you want to start working on #51 ? If it is done by Monday it will be great but if it takes more time we will promote it in next release.

**Comment by lazaa32** [comment]
We can implement sprites in next release as well.

**Comment by Kanahiro** [comment]
> https://docs.mapbox.com/mapbox-gl-js/style-spec/sprite/
In the specification, Sprites can be used in background-pattern, fill-pattern, line-pattern, fill-extrusion-pattern and icon-image.
I tried each points one by one, first, I've implemented fill-pattern-sprite.
I'll try line-pattern next.

**Comment by klokan** [comment]
The fill patterns implemented in the first version and are part of 1.1.0.

Additional sprites (icons) can be implemented in a follow-up ticket.

Thank you very much @Kanahiro
