### ISSUE TITLE
Plugin is not visible in Browser in QGIS 3.4 

### ISSUE THREAD

**Issue by daliborjanak** [maptiler/qgis-maptiler-plugin#7]
If I try to install the plugin in qgis 3.4 LTS. The Geocoding is present and I can correctly add maptiler key on it but there is no plugin displayed in a Browser. Tested on Mac and ubuntu. Console said that the plugin is correctly loaded. In the log, there is only one warning with depreciation:

```
2020-05-11T15:22:18     WARNING    warning:/usr/lib/python3/dist-packages/osgeo/gdal.py:112: DeprecationWarning: ogr.py was placed in a namespace, it is now available as osgeo.ogr
```

**Comment by Kanahiro** [comment]
Thank you for reviewing.
I also tested installing the plugin in QGIS3.4 on Mac and a problem that similar to you occurred.
Probably, some codes may have dependency on QGIS3.10.
Now Latest LTR is 3.10, does the plugin have to be available on 3.4?

**Comment by daliborjanak** [comment]
Good question I don't know :-)  If this is a quick fix than it could be better to fix it. I'm running Ubuntu 19.10  (so this is not an old system) and this version is the default for these packages...

**Comment by lazaa32** [comment]
Recently I installed QGIS from official repo and I have 3.10.
Also from https://qgis.org/en/site/forusers/download.html they say:

> The long-term repositories currently offer QGIS 3.10.5 'A Coruña'.
