### ISSUE TITLE
Review README and plugin metadata

### ISSUE THREAD

**Issue by lazaa32** [maptiler/qgis-maptiler-plugin#70]
Before release we need to review Readme and metadata of the plugin.
- [x] readme
Review readme
- [x] metada
Check name, email, author etc.
- [x] icon
Don't forget to add icon to plugin so it is visible in Plugin detail page in Plugin browser.
- [x] tags
Add matching tags so it is easier to find

**Comment by daliborjanak** [comment]
Readme and tags updated

**Comment by lazaa32** [comment]
Closed in this [commit](https://github.com/maptiler/qgis-maptiler-plugin/commit/c6b9eb48ab5143f03477f55be672f064143d5b5b)
