### ISSUE TITLE
Add new connection - contextual dialog on MapTiler

### ISSUE THREAD

**Issue by klokan** [maptiler/qgis-maptiler-plugin#8]
Contextual (right click) on "MapTiler" should open a "New connection" dialog.

This should allow people to add their own maps to the list of maps (alphabetically) and into the recent maps.

Mockups to be provided here.

**Comment by klokan** [comment]
Mockup for the updated dialog to be done with @daliborjanak first...

**Comment by klokan** [comment]
The mockup is now updated...

Also, the listing inside of the Browser is simplified - and hopefully makes the plugin easier to use. Contextual menus are specified too.

Latest mockups at:
https://docs.google.com/presentation/d/1CQKYTI9Bi_goKVVQogeFT4e26EsvvAG7f_73McdsEAk/edit#slide=id.g8766510354_0_0

**Comment by Kanahiro** [comment]
Thank you updating mockups.
I've already start implementing and have to confirm some points.

- Is "Recently used map" feature needed?
    - This feature is not suitable to Latest mockups, I think.
- Is "Use vector tiles" checkbox needed? 
    - It is possible to show "Add as Vector" only in version having QgsVectorTileLayer API.
- In add map from URL, do you mind if user have to input Raster or Vector separately?
    - Like following screenshot
<img width="250" alt="スクリーンショット 2020-05-26 13 39 47" src="https://user-images.githubusercontent.com/20744195/82861585-254d9000-9f58-11ea-96ed-d03061f79630.png">

**Comment by klokan** [comment]
- The recently used function can be removed - no other QGIS plugin in Browser has it.
- Use vector tiles checkbox defined now the "default" double-click option. "Add as Vector" should be visible only in QGIS versions which do support vector tiles.
- Having one URL input is better than having two. The user don't care - we can handle the difference in python code - and be clever there.

**Comment by lazaa32** [comment]
Even vector tiles have TileJSON. E.g. [TileJSON](https://api.maptiler.com/tiles/v3/tiles.json?key=m6dxIgKVTnvERWrCmvUm) for Basic style.
We need to add test to recognize whether JSON url leads to vector or raster map. Right now if I add TileJSON for vector map it is added as raster map.
@Kanahiro can you please have a look at this?
