### ISSUE TITLE
Use QgsNetworkAccessManager instead of urllib/requests

### ISSUE THREAD

**Issue by lazaa32** [maptiler/qgis-maptiler-plugin#80]
According to [Tips&Tricks](https://plugins.qgis.org/publish/) (bottom section):
`Plugins should make use of QgsNetworkAccessManager instead of using urllib2/requests/etc... which often fail to use correct proxy settings.`

**Comment by Kanahiro** [comment]
I found this issue needs more time. If any issue are not found now, it is better to postpone replacing them.

**Comment by lazaa32** [comment]
Yeah, don't worry. We can leave it for next release.

**Comment by lazaa32** [comment]
If you have time could you please look at #81. I would like to upload version 1.0.0 today and this issue would be nice to fix.

**Comment by nilsnolde** [comment]
This might save you some time:
https://github.com/GIScience/orstools-qgis-plugin/blob/master/ORStools/common/networkaccessmanager.py

I needed to do that too. All corporate proxies are failing otherwise. Originally from good ol' boundlessgeo.

**Comment by nyalldawson** [comment]
Don't use the networkaccessmanager.py class if you're targeting anything above 3.4. use QgsBlockingNetworkRequest instead

**Comment by nilsnolde** [comment]
Ah, might that old class be a potential cause for QGIS crashes @nyalldawson ? That’s actually been plaguing me for a while and I couldn’t trace it yet..

**Comment by nilsnolde** [comment]
Apparently it does:
https://gis.stackexchange.com/questions/343126/how-to-perform-sync-or-async-network-request-in-pyqgis

**Comment by nyalldawson** [comment]
Yep, that's a perfect summary!

**Comment by klokan** [comment]
Do we have user-reported problem on this point? For how many users it is an urgent issue?

**Comment by lazaa32** [comment]
Fixed in https://github.com/maptiler/qgis-maptiler-plugin/pull/159. Requests are now done using QgsNetworkAccessManager class.
