### ISSUE TITLE
Small font size on HiDPi screens

### ISSUE THREAD

**Issue by saberraz** [maptiler/qgis-maptiler-plugin#91]
Fonts are almost unreadable on hidpi screens and mobile phones:
![Screenshot_20200609-121523_Input](https://user-images.githubusercontent.com/2649047/84141687-7e82ec80-aa4b-11ea-932a-2e3b8bc1ef39.png)

**Comment by lazaa32** [comment]
Hi @saberraz,
thank you for feedback. We try to test the plugin on various displays. If you have a chance, could you test plugin from [HiDPI branch](https://github.com/maptiler/qgis-maptiler-plugin/tree/hidpi) on your display? Any feedback is appreciated, thanks.

**Comment by saberraz** [comment]
Hi @lazaa32 
Apologies for the late response.

I tried the hidpi branch and got pretty much the same result as master. I think the underlying issue is having font sizes for labels in Pixels. If I switch them to Points, I can get a consistent rendering size on all screens (my hidpi laptop screen - even without scaling, my HD external screen and my mobile.)

**Comment by lazaa32** [comment]
Thank you @saberraz for very helpful insight.
Plugin uses `QgsUnitTypes.RenderPoints` now for fonts. I also change unit type for line-width so hopefully they will look better on different displays.
Changes pushed to HiDPI branch, feel free to test and leave any comment. Thanks.
