### ISSUE TITLE
[decorations] i can't save project in gpkg

### ISSUE THREAD

**Issue by pigreco** [maptiler/qgis-maptiler-plugin#94]
By adding a decoration (Copyrigth) in a qgz project, it is not saved in the project. When the project is reopened, the decoration is no longer present.

I uninstalled the plugin and the project file works well, I always review the decoration.

OSGeo4W64 QGIS 3.12 and QGIS master

![image](https://user-images.githubusercontent.com/7631137/84248255-7a1d0900-ab09-11ea-8ac9-6efc7c960693.png)

**Comment by lazaa32** [comment]
@Kanahiro could you please have a look at this.
How to reproduce:
- add any layer from plugin
- update Copyright (remove, update, add custom copyright)
- updated copyright is correctly displayed
- save QGIS project
- open QGIS project
- default copyright is displayed, changes are not visible anymore
